### ISSUE TITLE
デモプロジェクトが欲しい

### ISSUE THREAD

**Issue by lmiller1990** [k-okina/vue-proxy-component#2]
このコンポーネントは便利そうですがデモがないので使い方が不明かもしれないです。

お願いします！簡単な方法はjsfiddle。例：https://jsfiddle.net/BeYond123/eywraw8t/141794/  （これでも使ってもいいです！）

**Comment by kahirokunn** [comment]
ありがとうございます！！！！！
そちら使わせていただきます！
